### ISSUE TITLE
Exception when submit report.

### ISSUE THREAD

**Issue by DavinAhn** [Buglife/buglife-android#17]
SDK Version:

0.9.14

Situation is like under:

1. Launch app.
2. Buglife initialization in `Application` subclass. (Used `SCREENSHOT` invocation method.)
3. Started `MainActivity` from `Application` subclass.
4. Did screenshot.
5. Submit report.
6. Exception occurred during dismissing `ReportActivity`.

Exception Log:
```
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@8adcd1f[Submitting bug report…] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:363)
       at android.app.Dialog.dismiss(Dialog.java:346)
       at com.buglife.sdk.ReportActivity$3.onSuccess(ReportActivity.java:209)
       at com.buglife.sdk.Client$6.onResponse(Client.java:531)
       at com.buglife.sdk.Client$6.onResponse(Client.java:528)
       at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Test Device:

Huawei Nexus 6P (Android 7.1.1) -- **Occurs only on this device.**

[Fabric](https://fabric.io)'s advice:

This is a crash caused by your app dismissing a dialog attached to an Activity which is finishing or finished. This can happen in a number of ways -- for example, if an AsyncTask is running while a ProgressDialog is showing, and the user rotates the device, causing the Activity to be recreated.

[1. View not attached to window manager crash](https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash)

**Comment by schukin** [comment]
Thanks for the detailed bug report @DaVinAhn! Just released v0.9.16, which includes a fix for this.
