### ISSUE TITLE
Dependency Volley not found.

### ISSUE THREAD

**Issue by ShaishavGandhi** [Buglife/buglife-android#27]
Version : 1.3.0

App crashes on Runtime with the following exception:
`com.buglife.sdk.Buglife$BuglifeException: Unable to initialize Buglife. Dependency `com.android.volley:volley` not found
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
                                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: com.buglife.sdk.Buglife$BuglifeException: Unable to initialize Buglife. Dependency `com.android.volley:volley` not found
                                                                       at com.buglife.sdk.Buglife.verifyDependencies(Buglife.java:255)
                                                                       at com.buglife.sdk.Buglife.initWithEmail(Buglife.java:66)
                                                                       at com.glassdoor.gdandroid2.app.GDApplication.initBugLife(GDApplication.java:704)
                                                                       at com.glassdoor.gdandroid2.app.GDApplication.onCreate(GDApplication.java:242)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)`

Possible things that might help about project setup:
1. We follow a multi-module setup. So BugLife is imported in a library project which is eventually consumed by an `application` project.

**Comment by schukin** [comment]
Hi @shaishavgandhi05 - Thanks for reporting this! To fix this, you'll need to explicitly import Volley as a dependency. We'll update the README to reflect this, please let me know if you continue to experience issues.

**Comment by ShaishavGandhi** [comment]
It doesn't make sense to place the dependency burden of the library on it's consumer. I see that you do import volley in the library. Why would i need to import it myself in the app?

**Comment by schukin** [comment]
You're absolutely right! This is actually a bug in the latest release of buglife-android 😬 We're working on fixing this our next release, but in the meantime we can only suggest either

1. Adding the dependency manually
2. Downgrading to buglife-android v1.2.4, which doesn't experience this issue

Sorry for the trouble. We're working on fixing this, and fixing it the *right* way.

**Comment by ShaishavGandhi** [comment]
Awesome! Thanks.

**Comment by ShaishavGandhi** [comment]
Hi @schukin , looks like 1.2.4 also has the same issue.

**Comment by alexfu** [comment]
I just updated to `1.3.1` and it's still throwing this error for me... 🤔

**Comment by balrampandey19** [comment]
Same here ,updated to 1.3.1 and still same error.

**Comment by vicky7230** [comment]
Updated to 1.3.1 and still same error.

**Comment by schukin** [comment]
Hi @vicky7230 - please update to 1.3.2, which should fix this issue.
