### ISSUE TITLE
The app is crashing if before sending a Bug report if you click on the captured screenshot and try to reopen it.

### ISSUE THREAD

**Issue by arnab-kundu** [Buglife/buglife-android#32]
The app is crashing if before sending a Bug report if you click on the captured screenshot and try to reopen it.

![device-2018-04-02-193515](https://user-images.githubusercontent.com/18009010/38199177-6574e8e2-36ad-11e8-953e-6ef4c87b3ce6.png)

This is the error log I am getting.

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.prime.xemplarinsights, PID: 23209
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'com.buglife.sdk.ApiIdentity com.buglife.sdk.BugContext.getApiIdentity()' on a null object reference
                                                                               at com.buglife.sdk.ScreenshotAnnotatorActivity$2.run(ScreenshotAnnotatorActivity.java:177)
                                                                               at android.os.Handler.handleCallback(Handler.java:810)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:189)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by arnab-kundu** [comment]
I would like to inform I am using latest versio0n i.e. compile 'com.buglife.sdk:buglife-android:1.3.1' in my gradle
