### ISSUE TITLE
Adding Custom Fields crashed during submission 

### ISSUE THREAD

**Issue by jibon57** [Buglife/buglife-android#40]
Hello,

When I am trying to add custom fields following this: https://buglife.com/docs/android/custom_fields it's showing fields in the report form. But when I am trying to submit that time getting following errors. This working fine without custom fields. **Note**: `I am using NativeScript to use this library.`

```
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.buglife.sdk.Attribute.getValue()' on a null object reference
System.err: 	at com.buglife.sdk.Report.toJSON(Report.java:43)
System.err: 	at com.buglife.sdk.BugReporterImpl.report(BugReporterImpl.java:56)
System.err: 	at com.buglife.sdk.Client.submitReport(Client.java:256)
System.err: 	at com.buglife.sdk.Buglife.submitReport(Buglife.java:239)
System.err: 	at com.buglife.sdk.ReportActivity.submitReport(ReportActivity.java:231)
System.err: 	at com.buglife.sdk.ReportActivity.onOptionsItemSelected(ReportActivity.java:167)
System.err: 	at android.app.Activity.onMenuItemSelected(Activity.java:3369)
System.err: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
System.err: 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
System.err: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
System.err: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
System.err: 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
System.err: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
System.err: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
System.err: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
System.err: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
System.err: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
System.err: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
System.err: 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
System.err: 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
System.err: 	at android.view.View.performClick(View.java:6213)
System.err: 	at android.widget.TextView.performClick(TextView.java:11074)
System.err: 	at android.view.View$PerformClick.run(View.java:23645)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6646)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by nosyjoe** [comment]
I had the same issue - it happens because the when you add a custom field, the summary field does not get added automatically, but is expected to be and then crashes. 

A simple workaround is to add the field explicitly in addition to your custom fields, e.g.:

```java
TextInputField stepsField = new TextInputField("Steps");
stepsField.setMultiline(true);
Buglife.setInputFields(TextInputField.summaryInputField(), stepsField);
```

This should probably be automated when one calls `Buglife.setInputFields()`

**Comment by jibon57** [comment]
@nosyjoe thank you very much !! It's working now. Is there any way to make the fields required? I mean at present anyone can avoid to fill up the field & submit report but I need to know few extra information. Is it possible to make the field compulsory to fill up?
