### ISSUE TITLE
Doesn't work with Material Themes

### ISSUE THREAD

**Issue by naturalwarren** [Buglife/buglife-android#53]
With material theming you don't set a `colorAccent`, without it buglife blows up.

```
 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300b5 a=5}
        at android.content.res.TypedArray.getColor(TypedArray.java:477)
        at com.buglife.sdk.ColorPalette$Builder.getColorFromAppStyleResources(ColorPalette.java:280)
        at com.buglife.sdk.ColorPalette$Builder.getColorFromAppStyleOrColorResources(ColorPalette.java:254)
        at com.buglife.sdk.ColorPalette$Builder.getBuglifeColorOrColorFromAppTheme(ColorPalette.java:225)
        at com.buglife.sdk.ColorPalette$Builder.build(ColorPalette.java:168)
        at com.buglife.sdk.ScreenshotAnnotatorActivity.onCreate(ScreenshotAnnotatorActivity.java:110)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
```

**Comment by schukin** [comment]
Thanks @naturalwarren! We're looking into this asap.

**Comment by danhd123** [comment]
Hi @naturalwarren, based on what you've told us, we've got a patch that *should* fix your issue. Try updating to buglife-android 1.4.2 and let us know if you're still encountering the issue, or any others for that matter.

-Daniel

**Comment by schukin** [comment]
@naturalwarren - just wanted to follow up to confirm, does this fix the crash you were seeing?

**Comment by naturalwarren** [comment]
I haven't bumped onto the latest version, yet.

**Comment by naturalwarren** [comment]
Works. Thank you!
