### ISSUE TITLE
Saving annotated screenshot fails

### ISSUE THREAD

**Issue by timc-mediamonks** [Buglife/buglife-android#58]
Sdk version: 1.4.3
Test device: pixel 3 android 9
Invocation method: screenshot

After adding some arrows, blurs etc, sending the report consistently produces this error
```
2019-05-29 14:37:31.625 21991-21991/? E/com.Buglife: Error saving screenshot!
java.io.FileNotFoundException: /storage/emulated/0/Pictures/Screenshots/Screenshot_20190529-143720.png (Permission denied)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:308)
at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
at com.buglife.sdk.ScreenshotAnnotatorActivity.k(ScreenshotAnnotatorActivity.java:293)
at com.buglife.sdk.ScreenshotAnnotatorActivity.onOptionsItemSelected(ScreenshotAnnotatorActivity.java:8229)
at android.app.Activity.onMenuItemSelected(Activity.java:3544)
at androidx.fragment.app.e.onMenuItemSelected(FragmentActivity.java:384)
at androidx.appcompat.app.c.onMenuItemSelected(AppCompatActivity.java:194)
at androidx.appcompat.view.i.onMenuItemSelected(WindowCallbackWrapper.java:109)
at androidx.appcompat.view.i.onMenuItemSelected(WindowCallbackWrapper.java:109)
at androidx.appcompat.app.j$2.a(ToolbarActionBar.java:64)
at androidx.appcompat.widget.Toolbar$1.a(Toolbar.java:207)
at androidx.appcompat.widget.ActionMenuView$d.a(ActionMenuView.java:781)
at androidx.appcompat.view.menu.g.a(MenuBuilder.java:840)
at androidx.appcompat.view.menu.i.b(MenuItemImpl.java:158)
at androidx.appcompat.view.menu.g.a(MenuBuilder.java:991)
at androidx.appcompat.widget.ActionMenuView.a(ActionMenuView.java:2981)
at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
at android.view.View.performClick(View.java:6597)
at android.view.View.performClickInternal(View.java:6574)
at android.view.View.access$3100(View.java:778)
at android.view.View$PerformClick.run(View.java:25885)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The report is sent, but only the original screenshot is attached, the annotations are lost.

**Comment by schukin** [comment]
Thanks for reporting this! We're working on a fix, and will release an update ASAP.

**Comment by danhd123** [comment]
Hi Tim, 

We're looking into this; in the meantime, can you give us a few more details?

Did you allow your app to access media/photos? If that permission is not granted, Buglife cannot watch for screenshots. 

What other SDKs are you using? In particular, are you using Vungle?

**Comment by danhd123** [comment]
Also if you have a sample project which reproduces this, that'd be awesome!

**Comment by timc-mediamonks** [comment]
> Did you allow your app to access media/photos? If that permission is not granted, Buglife cannot watch for screenshots.

Yes.. as you can see the error occurs in ScreenshotAnnotatorActivity.

The stacktrace above is slightly obfuscated, here is a clearer one

```
E/com.Buglife: Error saving screenshot!
    java.io.FileNotFoundException: /storage/emulated/0/Pictures/Screenshots/Screenshot_20190604-102735_BuglifeError.png (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at com.buglife.sdk.ScreenshotAnnotatorActivity.saveAnnotatedBitmap(ScreenshotAnnotatorActivity.java:293)
        at com.buglife.sdk.ScreenshotAnnotatorActivity.continueToReportActivity(ScreenshotAnnotatorActivity.java:229)
        at com.buglife.sdk.ScreenshotAnnotatorActivity.onOptionsItemSelected(ScreenshotAnnotatorActivity.java:206)
        at android.app.Activity.onMenuItemSelected(Activity.java:3450)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

The error occurs on android 8 and 9, but not on 7. Did not test on 6 and below.

I'm not using vungle. The issue is unrelated to other dependencies. I have a blank project here that demonstrates the issue: https://github.com/MediaMonksMobile/BuglifeError

**Comment by timc-mediamonks** [comment]
I already found the problem and am working on a fix, you can expect a PR later today

**Comment by danhd123** [comment]
Thanks, Tim, really awesome.
