### ISSUE TITLE
Record video fails on Android 10

### ISSUE THREAD

**Issue by duncancarroll** [Buglife/buglife-android#68]
Repro steps: Use BugLife screen record feature with `targetSdkVersion 29` on an Android 10 phone.

```
2019-10-25 10:53:08.341 29152-29152/audio.breaker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: audio.breaker, PID: 29152
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:2, request=12345, result=-1, data=Intent { (has extras) }} to activity {audio.breaker/audio.breaker.ui.HomeActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
        at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
        at com.buglife.sdk.screenrecorder.ScreenProjector.start(ScreenProjector.java:47)
        at com.buglife.sdk.screenrecorder.ScreenRecorder.startRecording(ScreenRecorder.java:132)
        at com.buglife.sdk.screenrecorder.ScreenRecorder.start(ScreenRecorder.java:61)
        at com.buglife.sdk.Client.startScreenRecordingFlow(Client.java:448)
        at com.buglife.sdk.Client.access$500(Client.java:51)
        at com.buglife.sdk.Client$6.onPermissionGranted(Client.java:413)
        at com.buglife.sdk.screenrecorder.ScreenRecordingPermissionHelper.onActivityResult(ScreenRecordingPermissionHelper.java:88)
        at android.app.Activity.dispatchActivityResult(Activity.java:8137)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by hossambusiness** [comment]
any fix for this yet?
