### ISSUE TITLE
Exception when restore PermissionHelper in other Activity.

### ISSUE THREAD

**Issue by DavinAhn** [Buglife/buglife-android#7]
SDK Version:

0.9.10

Situation is like under:

1. Start `Main Activity`.
2. Start `Sub Activity`.
3. Generating report and send. (Attached `PermissionHelper` to `Sub Activity`)
4. Finish `Sub Activity`.
5. Exception.

Exception Log:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.main/com.my.main.activity.MainActivityUniversal}: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.buglife.sdk.PermissionHelper: make sure class name exists, is public, and has an empty constructor that is public
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
  at android.app.ActivityThread.-wrap11(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5422)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.buglife.sdk.PermissionHelper: make sure class name exists, is public, and has an empty constructor that is public
  at android.app.Fragment.instantiate(Fragment.java:628)
  at android.app.FragmentState.instantiate(Fragment.java:106)
  at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1858)
  at android.app.FragmentController.restoreAllState(FragmentController.java:122)
  at android.app.Activity.onCreate(Activity.java:918)
  at com.my.main.activity.MainActivity.onCreate(MainActivity.kt:58)
  at com.my.main.activity.MainActivityUniversal.onCreate(MainActivityUniversal.kt:53)
  at android.app.Activity.performCreate(Activity.java:6251)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5422) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Caused by: java.lang.IllegalAccessException: java.lang.Class<com.buglife.sdk.PermissionHelper> is not accessible from java.lang.Class<android.app.Fragment>
  at java.lang.Class.newInstance(Native Method)
  at android.app.Fragment.instantiate(Fragment.java:613)
  at android.app.FragmentState.instantiate(Fragment.java:106) 
  at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1858) 
  at android.app.FragmentController.restoreAllState(FragmentController.java:122) 
  at android.app.Activity.onCreate(Activity.java:918) 
  at com.my.main.activity.MainActivity.onCreate(MainActivity.kt:58) 
  at com.my.main.activity.MainActivityUniversal.onCreate(MainActivityUniversal.kt:53) 
  at android.app.Activity.performCreate(Activity.java:6251) 
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5422) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Proposed solution:**

Please add `public` access modifiers in `PermissionHelper` class declare.

**Comment by alexfu** [comment]
@DaVinAhn Before a fix is applied, could you provide a little more context? Your steps to reproduce is a little unclear. Which invocation method (screenshot, shake, etc) are you using? What's `Main Activity` and what's `Sub Activity`? What do you mean when you say:

> Attached PermissionHelper to Sub Activity

Can you share your `MainActivity.onCreate` code since that's where the crash is happening (line 58)? I can't reproduce this so I'd like to see how exactly you're getting this error.

**Comment by DavinAhn** [comment]
@alexfu I'm sorry, I didn't have enough explanation.

I used `SCREENSHOT` invocation method. And, `Main Activity` and `Sub Activity` are my mistakes. It is a simple activity name. (ex: `Main Activity` -> `MainActivity`)

The specific steps are as follows:
1. Launch app.
2. Buglife initialization in `Application` subclass. (Used `SCREENSHOT` invocation method.)
3. Started `MainActivity` from `Application` subclass.
4. Started `SubActivity` from `MainActivity`.
5. Did screenshot. (At this time, `PermissionHelper` fragment is attached to `SubActivity` by `ScreenshotContentObserver.start`.)
6. Submit report in `ReportActivity`.
7. Finish `SubActivity` and tried to switch to `MainActivity`. ([`FragmentManager`](https://developer.android.com/reference/android/app/FragmentManager.html) attempts to remove `PermissionHelper` fragment from `SubActivity` and restore it to `MainActivity` at `MainActivity.onCreate`.)
8. But, exception occurred during switchover. (Because `PermissionHelper` class is not known at the time of `MainActivity.onCreate`.)

Line 58 of `MainActivity` is:
```kotlin
57 override fun onCreate(savedInstanceState: Bundle?) { 
58     super.onCreate(savedInstanceState) 
59     ...
60 }
```

Test Device is:

Nexus 5X, Android 6.0.1

Thank you for your comment.
